### ISSUE TITLE
load_dataset报错

### ISSUE THREAD

**Issue by zhangsone** [fanyin3639/Rethinking-instruction-effectiveness#1]
Hello, I would like to ask, I downloaded the dataset to the local, and when loading the dataset, I reported KeyError: 'Instance License', later I found that from the load_dataset can enter the ni_dataset.py, but the passed data_dir is empty。

raw_datasets = load_dataset(
        "src/ni_dataset.py",
        data_dir=data_args.data_dir,
        task_dir=data_args.task_dir,
        cl_dir=data_args.cl_dir,
        cache_dir=model_args.cache_dir,
        max_num_instances_per_task=data_args.max_num_instances_per_task,
        max_num_instances_per_eval_task=data_args.max_num_instances_per_eval_task
    )

KeyError: 'Instance License'

**Comment by fanyin3639** [comment]
Please follow the train_t5.sh script to put your downloaded task data under data/tasksand try again. data_dir should contain the task names for the train/dev/test splits. You don't want to modify the current data_dir and I already stored the split there.

**Comment by zhangsone** [comment]
Yes, I have put the downloaded data in the data/tasks directory, but the same error is reported. Here are some of my errors:


07/13/2023 10:19:59 - WARNING - datasets.builder - Using custom data configuration default-e9d307844c9769e9
07/13/2023 10:19:59 - INFO - datasets.builder - Generating dataset natural_instructions (./cache/natural_instructions/default-e9d307844c9769e9/2.0.0/91897c26c38a0a5edb2db0a6a76fe7b25e8a8ef347126da0c18572fa576a3590)
Downloading and preparing dataset natural_instructions/default to ./cache/natural_instructions/default-e9d307844c9769e9/2.0.0/91897c26c38a0a5edb2db0a6a76fe7b25e8a8ef347126da0c18572fa576a3590...
07/13/2023 10:20:05 - INFO - datasets.builder - Dataset not on Hf google storage. Downloading and preparing it from source
07/13/2023 10:20:05 - INFO - datasets.utils.info_utils - Unable to verify checksums.
07/13/2023 10:20:05 - INFO - datasets.builder - Generating split train
Traceback (most recent call last):
  File "../src/run_s2s.py", line 628, in <module>
    main()
  File "../src/run_s2s.py", line 347, in main
    raw_datasets = load_dataset(
  File "/home/zl/.conda/envs/instruction/lib/python3.8/site-packages/datasets/load.py", line 1694, in load_dataset
    builder_instance.download_and_prepare(
  File "/home/zl/.conda/envs/instruction/lib/python3.8/site-packages/datasets/builder.py", line 597, in download_and_prepare
    self._download_and_prepare(
  File "/home/zl/.conda/envs/instruction/lib/python3.8/site-packages/datasets/builder.py", line 685, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/home/zl/.conda/envs/instruction/lib/python3.8/site-packages/datasets/builder.py", line 1084, in _prepare_split
    example = self.info.features.encode_example(record)
  File "/home/zl/.conda/envs/instruction/lib/python3.8/site-packages/datasets/features/features.py", line 1099, in encode_example
    return encode_nested_example(self, example)
  File "/home/zl/.conda/envs/instruction/lib/python3.8/site-packages/datasets/features/features.py", line 861, in encode_nested_example
    return {
  File "/home/zl/.conda/envs/instruction/lib/python3.8/site-packages/datasets/features/features.py", line 861, in <dictcomp>
    return {
  File "/home/zl/.conda/envs/instruction/lib/python3.8/site-packages/datasets/utils/py_utils.py", line 153, in zip_dict
    yield key, tuple(d[key] for d in dicts)
  File "/home/zl/.conda/envs/instruction/lib/python3.8/site-packages/datasets/utils/py_utils.py", line 153, in <genexpr>
    yield key, tuple(d[key] for d in dicts)
KeyError: 'Instance License'

**Comment by zhangsone** [comment]
At the same time, may I ask whether metadata experiment is the third experiment in your paper?

**Comment by fanyin3639** [comment]
> At the same time, may I ask whether metadata experiment is the third experiment in your paper?

This is for the metadata row in Table 2.

I don't know the exact reason for this error as the code runs fine on my end. Looks like there is a missing key and I hypothesis it can be a different version of data.

**Comment by wlmnzf** [comment]
Same problem, so I would like to ask which version of the dataset are you using?

**Comment by wlmnzf** [comment]
Dataset v2.7 works, the latest version v2.8 add the "Instance License"([#776](https://github.com/allenai/natural-instructions/pull/776)) @fanyin3639 @zhangsone 

> > At the same time, may I ask whether metadata experiment is the third experiment in your paper?
> 
> This is for the metadata row in Table 2.
> 
> I don't know the exact reason for this error as the code runs fine on my end. Looks like there is a missing key and I hypothesis it can be a different version of data.
